BookMarket/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookMarket.Models.DataBase;
using Microsoft.AspNetCore.Authorization;
using BookMarket.Models.ViewModels.Authors;
using BookMarket.Models.ViewModels.SearchBook;

namespace BookMarket.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly BookMarketContext _context;

        public AuthorsController(BookMarketContext context)
        {
            _context = context;
        }

        // GET: Authors
        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Author.ToListAsync());
        }

        // GET: Authors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Author
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            DetailViewModel vm = new DetailViewModel()
            {
                author = author,
                books = await _context.Book
                .OrderByDescending(i => i.AddDatabase)
                // Фильтруем по ключевому слову
                .Where(i => i.IdAuthor == (int)id)
                .Select(i =>
                new BookViewModel
                {
                    Id = i.Id,
                    AddDatabase = i.AddDatabase,
                    CategoryName = i.IdCategoryNavigation.Name,
                    Name = i.Name,
                    IdAuthor = (int)i.IdAuthor,
                    AuthorNameFamily = i.IdAuthorNavigation.NameFamily,
                    Description = i.Description,
                    PosterBook = i.PosterBook,
                    RatingBook = i.UserRating.Average(i => i.Mark)
                })
                .ToListAsync()
            };

            return View(vm);
        }

        // GET: Authors/Create
        [Authorize(Roles = "Администратор")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> Create([Bind("Id,Name,Family,Surname,DateBirth")] Author author)
        {
            if (ModelState.IsValid)
            {
                _context.Add(author);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Edit/5
        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Author.FindAsync(id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Family,Surname,DateBirth")] Author author)
        {
            if (id != author.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(author);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Author
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var author = await _context.Author.FindAsync(id);
            _context.Author.Remove(author);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorExists(int id)
        {
            return _context.Author.Any(e => e.Id == id);
        }
    }
}

BookMarket/Controllers/HomeController.cs
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BookMarket.Models;
using BookMarket.Models.DataBase;
using Microsoft.EntityFrameworkCore;
using System;
using BookMarket.Models.ViewModels.HomeViewModels;
using System.Threading.Tasks;
using BookMarket.Models.ViewModels.SearchBook;
using BookMarket.Services.Books;
using BookMarket.Services;
using BookMarket.Models.UsersIdentity;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using System.Text.Json;
using BookMarket.Services.Genres;
using Microsoft.Extensions.DependencyInjection;

namespace BookMarket.Controllers
{



    public class HomeController : Controller
    {

        public IBookService serviceBooks { get; private set; }
        public IUserService userService { get; private set; }
        public IGenresService genresService { get; private set; }



        #region Тесты

        public HomeController(IBookService serviceBooks)
        {
            this.serviceBooks = serviceBooks;
        }


        public HomeController(IUserService userService, IGenresService genresService)
        {
            this.userService = userService;
            this.genresService = genresService;
        }

        #endregion


        [ActivatorUtilitiesConstructor]
        public HomeController(IGenresService genresService, IBookService serviceBooks, IUserService userService)
        {
            this.userService = userService;
            this.serviceBooks = serviceBooks;
            this.genresService = genresService;
        }


        /// <summary>
        /// Выборка последних комментируемых книг
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<PartialViewResult> LastCommentsBook(int count = 4)
        {
            var lastCommentBooks = await serviceBooks.GetLastCommentaries(count);

            return PartialView("newComments", lastCommentBooks);
        }

        /// <summary>
        /// Выборка недавно добавленных книг
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> newBooks(int count = 4)
        {
            var newBooks = await serviceBooks.GetNewsBooks(count);

            return PartialView("booksData", newBooks);
        }

        /// <summary>
        /// Выборка топовых книг
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> topBooks(int count = 4)
        {

            // Получаем айдишники топовых книг

            var books = await serviceBooks.GetTopBooks(count);
            


            return PartialView("topBooksData", books);

        }


        [HttpGet]
        public async Task<IActionResult> IndexData(int genresCount = 8, int subGenresCount = 3, int topUsers = 10, int newUsers = 10)
        {

            IndexViewModel vm = new IndexViewModel()
            {

                CategoryGenres = await genresService.GetGenresSubCategories(genresCount, subGenresCount),

                topUsers = await userService.GetTopUsers(topUsers),
                NewUsers = await userService.GetNewUsers(newUsers)
            };



            return PartialView(vm);
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Privacy()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View();
        }
    }
}

BookMarket/Controllers/ProfileController.cs
using BookMarket.Models.UsersIdentity;
using BookMarket.Models.ViewModels.Profile;
using BookMarket.Services.Books;
using BookMarket.Services.Profile;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BookMarket.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly IProfileService profileService;
        private readonly IBookService bookService;

        public ProfileController(IProfileService profileService, IBookService bookService)
        {
            this.bookService = bookService;
            this.profileService = profileService;            
        }
        

        [HttpGet]
        public IActionResult Index(string name)
        {
            return View("Index", name);
        }


        [HttpGet]
        public async Task<IActionResult> FavoriteBooksUser(string name)
        {
            var data = await bookService.GetFavoritesBooks(name);

            return PartialView("FavoriteBooksUser", data);
        }

        [HttpGet]
        public async Task<IActionResult> AboutProfile(string name)
        {
            var user = await profileService.GetUser(name);

            IndexProfileViewModel vm = new IndexProfileViewModel()
            {
                email = name,
                user = user
            };

            return PartialView("ProfileData", vm);
        }

        [HttpGet]
        public async Task<IActionResult> LastVisitBooks(string name)
        {
            // Запрос на книги
            var query = await bookService.GetLastVisitBook(name);


            return PartialView(query);
        }

        [HttpGet]
        public async Task<IActionResult> GetFavoriteBooks(string UserName)
        {
            // Запрос на книги
            //var query = await bookService.GetLastVisitBook(name);


            return PartialView();
        }

        [HttpGet]
        public async Task<IActionResult> GetCommentaries(string name)
        {
            // Запрос на комментарии
            var query = await bookService.GetLastCommentariesUser(name);

            return PartialView("Commentaries", query);
        }



        [HttpPost]
        public async Task<IActionResult> LoadAvatar()
        {
            // Получаем файл
            var file = Request.Form.Files.FirstOrDefault();


            byte[] imageData = null;

            //считываем переданный файл в массив байтов
            using (var binaryReader = new BinaryReader(file.OpenReadStream()))
            {
                imageData = binaryReader.ReadBytes((int)file.Length);
            }

            // Обновляем аватар
            var updated = await profileService.UpdateAvatar(User.Identity.Name, imageData);

            if (!updated)
                return NotFound();

            return Redirect($"{User.Identity.Name}");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAvatar(string name)
        {
            if (name == User.Identity.Name)
            {
                var deleted = await profileService.RemoveUserAvatar(User.Identity.Name);

                if (!deleted)
                    return null;
            }

            return Redirect($"{name}");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveProfile(IndexProfileViewModel vm)
        {
            if (ModelState.IsValid)
            {
                if (vm.email == User.Identity.Name)
                {
                    var updated = await profileService.UpdateUser(vm);

                    if (updated == true)
                        return Redirect($"{vm.email}");
                }
            }

            return View();
        }
    }
}

BookMarket/Controllers/SearchBookController.cs
using BookMarket.Models.DataBase;
using BookMarket.Models.ViewModels.SearchBook;
using BookMarket.Services.Books;
using BookMarket.Services.Genres;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace BookMarket.Controllers
{
    public class SearchBookController : Controller
    {
        IBookService bookService;
        IGenresService genresService;

        public SearchBookController(IGenresService genresService, IBookService bookService)
        {
            this.bookService = bookService;
            this.genresService = genresService;
        }


        [HttpGet]
        public async Task<IActionResult> getData(int IdGenre = 0, int page = 0, string word = null, byte RatingOrdered = 0)
        {
            var books = await bookService.GetSearchBooks(IdGenre, page, word, RatingOrdered);

            // Выбираем первые 50 слов
            foreach (var item in books)
                item.Description = item.Description != null ? string.Join(' ', item.Description.Split(' ').Take(50)) : null;

            var genre = await genresService.FindGenreBook(IdGenre);

            getDataViewModel vm = new getDataViewModel()
                {
                    RatingOrdered = RatingOrdered == 1 ? true : false,
                    IdGenre = IdGenre,
                    InputWord = word,
                    page = page, // Текущая страница
                    MaxCountBooks = await bookService.getCountsBooks(word, (ushort)IdGenre), // Максимальное количество книг в выборке
                    books = books,
                    GenreName = genre?.Name
                };



            return PartialView("SearchedBooks", vm);
        }

        [HttpGet]
        public async Task<IActionResult> LastVisitBooks(string name)
        {
            if (User.Identity.IsAuthenticated)
            {
                // Запрос на книги
                var query = await bookService.GetLastVisitBook(name, 5);

                return PartialView(query);
            }
            



            

            return null;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string word, int idGenre, bool RatingOrdered = false)
        {
            SearchBookIndexVM vm = new SearchBookIndexVM()
            {
                RatingOrdered = RatingOrdered,
                IdGenre = idGenre,
                WordInput = word,
                // Выборка жанров с поджанрами с количеством книг
                CategoryGenres = await genresService.getGenresSubCategoriesCounts()
            };

            return View(vm);
        }
    }
}

BookMarket/Views/Home/Index.cshtml
@*@model BookMarket.Models.ViewModels.HomeViewModels.IndexViewModel*@

@{
    ViewData["Title"] = "Главная страница";
}


<section class="text-center main_page">
    <h1 class="display-4">Электронная библиотека</h1>
    <section>
        <a asp-controller="SearchBook" asp-action="Index" method="get">
            <div>
                <h2 class="text-center">Новинки на сайте</h2>
            </div>
        </a>
        <div id="new-books-data" class="row newsBook__groups">

        </div>
    </section>
    <section>
        <a class="mainPage__link" asp-controller="SearchBook" asp-action="Index" asp-route-RatingOrdered="true" method="get">
            <div>
                <h2 class="text-center">Популярные книги на сайте</h2>
            </div>
        </a>
        <div id="top-books-data" class="row newsBook__groups">

        </div>
    </section>
    <section class="lastCommentsBooks">
        <h2 class="text-center">Новые комментарии</h2>
        <div id="last-comments-books-data" class="row newsBook__groups">

        </div>
    </section>

</section>



<div id="content">

</div>

@section Scripts {
    <script>

        $(document).ready(function () {
            $.ajax({
                type: "GET",
                url: '/Home/newBooks',

                success: function (data) {
                    $("#new-books-data").html(data);
                }
            });

            $.ajax({
                type: "GET",
                url: '/Home/topBooks',

                success: function (data) {
                    $("#top-books-data").html(data);
                }
            });

            $.ajax({
                type: "GET",
                url: '/Home/LastCommentsBook',

                success: function (data) {
                    $("#last-comments-books-data").html(data);
                }
            });


            $.ajax({
                type: "GET",
                url: '/Home/IndexData',

                success: function (data) {
                    $("#content").html(data);
                }
            });
        })


    </script>
}

BookMarket/Views/Home/IndexData.cshtml
@model BookMarket.Models.ViewModels.HomeViewModels.IndexViewModel



<section class="text-center main_page">
    <section class="genresBlock">
        <div class="container">
            <h2 class="text-center">Жанры</h2>
            <div class="separator"></div>
            <ul class="row">
                @foreach (var item in Model.CategoryGenres)
                {
                    <li class="text-left col-lg-3 col-md-6 col-sm-6 col-6">
                        <h5>@item.Key.Name</h5>
                        <ul class="genreContent">
                            @foreach (var link in item.Value)
                            {
                                <li><a asp-controller="SearchBook" asp-action="Index" asp-route-idGenre="@link.Id" asp-route-name="@link.Name">@link.Name</a></li>
                            }
                            @*<li><a href="#">Подробнее</a></li>*@
                        </ul>
                    </li>
                }
            </ul>

        </div>
    </section>
    <section class="UsersRating text-center container-fluid px-0 mx-0">
        <h3 class="text-center">Рейтинг читателей</h3>
        <div class="CommentaryBox CommentaryBox__header container">
            <div class="row commentator align-items-center">
                <div class="col-1 commentator_number">
                    №
                </div>
                <div class="col-5 commentator_data">
                    Пользователь
                </div>
                <div class="col-3 commentator__TotalRating">
                    Количество оценок
                </div>
                <div class="col-2 col-md-3 commentator__stars">
                    Средний балл
                </div>
            </div>
        </div>
        @{
            int count = 1;
            @foreach (var item in Model.topUsers)
            {
                <div class="CommentaryBox container">
                    <a asp-controller="Profile" asp-action="Index" asp-route-name="@item.Name">
                        <div class="row commentator align-items-center">
                            <div class="col-1 col-md-1 px-0 commentator_ava text-center">
                                @(count++)
                            </div>
                            <div class="col-6 col-md-5 commentator_ava">
                                <div class="container mx-0 px-0">
                                    <div class="row align-items-center  ">
                                        <div class="col-3 px-0">
                                            @if (item.Ava != null)
                                            {
                                                <img src="data:image;base64, @System.Convert.ToBase64String(item.Ava)" alt="avatar">
                                            }
                                            else
                                            {
                                                <img src="~/Images/avatar.png" alt="avatar">
                                            }
                                        </div>
                                        <div class="col px-0">
                                            @item.Name
                                        </div>
                                    </div>
                                </div>



                            </div>

                            <div class="col-2 px-0 col-md-3 commentator__ava">
                                @item.TotalComments
                            </div>
                            <div class="col-md-3 mx-0 px-0 col-3 commentator__stars">
                                @item.AvgRating <span>★</span>
                            </div>
                        </div>
                    </a>
                </div>
            }
        }

    </section>
    <section class="UsersRating text-center container-fluid px-0 mx-0">
        <h3 class="text-center">Новые пользователи</h3>
        <div class="CommentaryBox CommentaryBox__header container">
            <div class="row commentator align-items-center">
                <div class="col-2 commentator_number">
                    №
                </div>
                <div class="col-6 commentator_data">
                    Пользователь
                </div>
                <div class="col-4">
                    Дата регистрации
                </div>
            </div>
        </div>
        @{
            count = 1;
            @foreach (var item in Model.NewUsers)
            {
                <div class="CommentaryBox container">
                    <a asp-controller="Profile" asp-action="Index" asp-route-name="@item.Name">
                        <div class="row commentator align-items-center">
                            <div class="col-2 col-md-2 px-0 commentator_ava text-center">
                                @(count++)
                            </div>
                            <div class="col-6 col-md-6 commentator_ava">
                                <div class="container mx-0 px-0">
                                    <div class="row align-items-center  ">
                                        <div class="col-3 px-0">
                                            @if (item.Ava != null)
                                            {
                                                <img src="data:image;base64, @System.Convert.ToBase64String(item.Ava)" alt="avatar">
                                            }
                                            else
                                            {
                                                <img src="~/Images/avatar.png" alt="avatar">
                                            }
                                        </div>
                                        <div class="col px-0">
                                            @item.Name
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-4 px-0 commentator_ava text-center">
                                @item.dateRegistration.ToString("F")
                            </div>
                        </div>
                    </a>
                </div>
            }
        }

    </section>
</section>

BookMarket/Views/Home/booksData.cshtml
@model List<BookMarket.Models.ViewModels.HomeViewModels.IndexBook>



@foreach (var item in Model)
{
    <div class="bookData col-xs-12 col-sm-6 col-md-3 col-centered col-min">
        <div class="bookData__image">
            <a asp-action="AboutBook" asp-controller="Books" asp-route-id="@item.Id">
                <img src="data:image;base64, @System.Convert.ToBase64String(item.PosterBook)" />
            </a>
        </div>
        <div class="bookData__name">
            <a asp-action="AboutBook" asp-controller="Books" asp-route-id="@item.Id" asp-route-name="@item.Name">
                <h3>@item.Name</h3>
            </a>
        </div>
        <div class="bookData__rating">
            @if (item.RatingBook != 0)
            {
                <h6>Рейтинг @item.RatingBook.ToString("0.00") <span>★</span></h6>
            }
            else
            {
                <h6>Нет рейтинга</h6>
            }
        </div>
        <div class="bookData_author">
            <a asp-action="Details" asp-controller="Authors" asp-route-id="@item.IdAuthor" asp-route-name="@item.AuthorNameFamily">
                <h4>@item.AuthorNameFamily</h4>
            </a>
        </div>
    </div>
}

BookMarket/Views/Home/newComments.cshtml
@model IEnumerable<BookMarket.Models.ViewModels.SearchBook.BookViewModel>


@foreach (var item in Model)
{
    <div class="bookData col-xs-12 col-sm-6 col-md-3 col-centered col-min">
        <div class="bookData__image">
            <a asp-action="AboutBook" asp-controller="Books" asp-route-id="@item.Id">
                <img src="data:image;base64, @System.Convert.ToBase64String(item.PosterBook)" />
            </a>
        </div>
        <div class="bookData__name">
            <a asp-action="AboutBook" asp-controller="Books" asp-route-id="@item.Id" asp-route-name="@item.Name">
                <h3>@item.Name</h3>
            </a>
        </div>
        <div class="bookData__rating">
            @if (item.RatingBook != 0)
            {
                <h6>Рейтинг @item.RatingBook.ToString("0.00") <span>★</span></h6>
            }
            else
            {
                <h6>Нет рейтинга</h6>
            }
        </div>
        <div class="bookData_author">
            <a asp-action="Details" asp-controller="Authors" asp-route-id="@item.IdAuthor" asp-route-name="@item.AuthorNameFamily">
                <h4>@item.AuthorNameFamily</h4>
            </a>
        </div>
    </div>
}

BookMarket/Views/Home/topBooksData.cshtml
@model List<BookMarket.Models.ViewModels.HomeViewModels.IndexBook>


@foreach (var item in Model)
{
    <div class="bookData col-xs-12 col-sm-6 col-md-3 col-centered col-min">
        <div class="bookData__image">
            <a asp-action="AboutBook" asp-controller="Books" asp-route-id="@item.Id">
                <img src="data:image;base64, @System.Convert.ToBase64String(item.PosterBook)" />
            </a>
        </div>
        <div class="bookData__name">
            <a asp-action="AboutBook" asp-controller="Books" asp-route-id="@item.Id" asp-route-name="@item.Name">
                <h3>@item.Name</h3>
            </a>
        </div>
        <div class="bookData__rating">
            @if (item.RatingBook != 0)
            {
                <h6>Рейтинг @item.RatingBook.ToString("0.00") <span>★</span></h6>
            }
            else
            {
                <h6>Нет рейтинга</h6>
            }
        </div>
        <div class="bookData_author">
            <a asp-action="Details" asp-controller="Authors" asp-route-id="@item.IdAuthor" asp-route-name="@item.AuthorNameFamily">
                <h4>@item.AuthorNameFamily</h4>
            </a>
        </div>
    </div>
}