BookMarket/Components/UserViewComponent.cs
using BookMarket.Models.UsersIdentity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookMarket.Components
{

    /// <summary>
    /// Компонент для возвращения модели юзера
    /// </summary>
    [ViewComponent]
    public class UserViewComponent : ViewComponent
    {
        private readonly UserManager<User> _userManager;

        public UserViewComponent(UserManager<User> userManager)
        {
            this._userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {            
            var user = await _userManager.FindByEmailAsync(User.Identity.Name);

            if (user == null)
                return null;

            return View("AboutUser", user);
        }

    }
}

BookMarket/Controllers/RolesController.cs
using BookMarket.Models.Roles;
using BookMarket.Models.UsersIdentity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookMarket.Controllers
{
    [Authorize(Roles = "Администратор")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;

        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View(_roleManager.Roles.ToList());
        }

        [HttpGet]
        public IActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }

            return View(name);

            
        }


        [HttpGet]
        public async Task<IActionResult> Edit(string userId)
        {
            // Находим юзера
            var user = await _userManager.FindByIdAsync(userId);

            if (user != null)
            {
                // получем список ролей пользователя и все роли
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                
                EditRoleViewModel vm = new EditRoleViewModel()
                {
                    UserId = userId,
                    UserEmail = user.Email,
                    AllRoles = allRoles,
                    UserRoles = userRoles
                };

                return View(vm);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);


                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("Index", "Users");
            }

            return NotFound();
        }
    }
}

BookMarket/Controllers/SearchBookController.cs
using BookMarket.Models.DataBase;
using BookMarket.Models.ViewModels.SearchBook;
using BookMarket.Services.Books;
using BookMarket.Services.Genres;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace BookMarket.Controllers
{
    public class SearchBookController : Controller
    {
        IBookService bookService;
        IGenresService genresService;

        public SearchBookController(IGenresService genresService, IBookService bookService)
        {
            this.bookService = bookService;
            this.genresService = genresService;
        }


        [HttpGet]
        public async Task<IActionResult> getData(int IdGenre = 0, int page = 0, string word = null, byte RatingOrdered = 0)
        {
            var books = await bookService.GetSearchBooks(IdGenre, page, word, RatingOrdered);

            // Выбираем первые 50 слов
            foreach (var item in books)
                item.Description = item.Description != null ? string.Join(' ', item.Description.Split(' ').Take(50)) : null;

            var genre = await genresService.FindGenreBook(IdGenre);

            getDataViewModel vm = new getDataViewModel()
                {
                    RatingOrdered = RatingOrdered == 1 ? true : false,
                    IdGenre = IdGenre,
                    InputWord = word,
                    page = page, // Текущая страница
                    MaxCountBooks = await bookService.getCountsBooks(word, (ushort)IdGenre), // Максимальное количество книг в выборке
                    books = books,
                    GenreName = genre?.Name
                };



            return PartialView("SearchedBooks", vm);
        }

        [HttpGet]
        public async Task<IActionResult> LastVisitBooks(string name)
        {
            if (User.Identity.IsAuthenticated)
            {
                // Запрос на книги
                var query = await bookService.GetLastVisitBook(name, 5);

                return PartialView(query);
            }
            



            

            return null;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string word, int idGenre, bool RatingOrdered = false)
        {
            SearchBookIndexVM vm = new SearchBookIndexVM()
            {
                RatingOrdered = RatingOrdered,
                IdGenre = idGenre,
                WordInput = word,
                // Выборка жанров с поджанрами с количеством книг
                CategoryGenres = await genresService.getGenresSubCategoriesCounts()
            };

            return View(vm);
        }
    }
}

BookMarket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Электронная бесплатная онлайн библиотека - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/mainpage.css" rel="stylesheet" />
    <link href="~/css/test.css" rel="stylesheet" />
    <link rel="canonical" href="https://market-books.ru" />
    <meta name="author" content="Андрей Радюкевич">
    <meta name="robots" content="index, follow"/>
    <meta name="copyright" content="Все права принадлежат Андрею Радюкевичу">
    <meta name="keywords" content="читать книги онлайн без регистрации, читать книги про бизнес, читать любовные романы, бесплатная электронная библиотека">
    <meta name="description" content="Электронная бесплатная онлайн библиотека | читать бесплатно книги">
    @RenderSection("Css", required: false)
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
        (function (m, e, t, r, i, k, a) {
            m[i] = m[i] || function () { (m[i].a = m[i].a || []).push(arguments) };
            m[i].l = 1 * new Date(); k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a)
        })
            (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

        ym(70363165, "init", {
            clickmap: true,
            trackLinks: true,
            accurateTrackBounce: true
        });
    </script>
    <!-- /Yandex.Metrika counter -->
</head>
<body>
    <header>
        <nav class="menu navbar navbar-expand-md navbar-toggleable-md navbar-light  box-shadow mb-1">
            <div class="container">
                <a class="navbar-brand text-light" asp-controller="Home" asp-action="Index">market-books</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-md-inline-flex flex-md-row">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="SearchBook" asp-action="Index" asp-route-RatingOrdered="true" method="get">Рейтинг книг</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Privacy">Проект</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Администратор"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Books" asp-action="AddBook">Добавить книгу</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Users" asp-action="Index">Пользователи</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Roles" asp-action="Index">Роли</a>
                            </li>
                        }
                    </ul>
                    <div class="auth__div">
                        @if (User.Identity.IsAuthenticated)
                        {
                            @await Component.InvokeAsync("User")
                        }
                        else
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-controller="Account" asp-action="Login">Вход</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-controller="Account" asp-action="Register">Регистрация</a>
                                </li>
                            </ul>
                        }
                    </div>
                </div>
            </div>
        </nav>
        <div class="container header">
            <div class="row">
                <div class="col">
                    <form asp-controller="SearchBook" asp-action="Index" method="get">
                        <div class="searchBook-input input-group">
                            <span class="fa fa-search text-center"></span>
                            <input id="inputWord" name="word" type="text" class="form-control search" placeholder="Поиск по названию книги, автора">
                            <button class="btn mybtn" type="submit">Поиск</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </header>

    <div class="content container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center">
                    <a asp-area="" asp-controller="Home" asp-action="Privacy">
                        &copy; 2020 - market-books
                    </a>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://use.fontawesome.com/056ddd099c.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>


    @RenderSection("Scripts", required: false)
</body>

</html>